### ISSUE TITLE
Deleting files should not move the cursor to the top

### ISSUE THREAD

**Issue by duganchen** [sayanarijit/xplr#693] opened 2024-02-11 19:06 UTC
When I delete a file with "dD", the cursor gets moved to the top of the directory. I find this annoying, and I would much prefer for the cursor to be moved to a more reasonable place. Say, the file immediately before the first file in the selection to be removed, or the file immediately after.

**Comment by sayanarijit** [comment] 2024-02-12 06:06
I can't reproduce this. Are you on the latest version and using [this similar default config](https://github.com/sayanarijit/xplr/blob/main/src/init.lua)?

**Comment by sayanarijit** [comment] 2024-02-12 06:17
https://github.com/sayanarijit/xplr/assets/11632726/492bb394-3ac1-47bc-a60a-8a34b6d8e487

**Comment by sayanarijit** [comment] 2024-05-06 01:53
Closing this.

**Closed by sayanarijit** 2024-05-06 01:53 UTC
