### ISSUE TITLE
panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64'

### ISSUE THREAD

**Issue by Zakyramadhan1** [sayanarijit/xplr#626] opened 2023-06-03 09:01 UTC
with the 0.21.1 version, i just update it and it says:
```
thread '<unnamed>' panicked at 'assertion failed: tv_nsec >= 0 && tv_nsec < NSEC_PER_SEC as i64', library/std/src/sys/unix/time.rs:77:9
                                                                                                                                       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                              [1]    318 IOT instruction  xplr
```
but with musl it just work fine but there is a warning: 
```
libunwind: __unw_add_dynamic_fde: bad fde: FDE is realy CIE
```
it think it is because i use gnu libc and not musl libc
OS: Artix linux(runit)
Terminal: Kitty
Shell: zsh (also bash has the same error)
Rust: 1.69.0
Compositor: Hyprland (Wayland)

**Comment by sayanarijit** [comment] 2023-06-03 09:07
Duplicate of https://github.com/sayanarijit/xplr/issues/565

**Closed by sayanarijit** 2023-06-03 09:07 UTC
