### ISSUE TITLE
Pattern matching in `node_type`

### ISSUE THREAD

**Issue by RustemB** [sayanarijit/xplr#194] opened 2021-05-24 12:40 UTC
for exampe
```lua
xplr.config.node_types.mime_essence = {
	["video/*"] = {
		meta = { icon = "📽" },
	}
}
```
to match all video types

**Comment by sayanarijit** [comment] 2021-05-24 12:57
Pattern matching might be a little difficult to implement and might have performance costs. But I think it'll be possible to implement nested mime types.

E.g.

```
video = {
  default = ...
  mp4 = ...
}
```

**Comment by bew** [comment] 2021-05-24 13:24
I'm curious, what would be difficult to implement here?

**Comment by sayanarijit** [comment] 2021-05-24 13:26
Going through the keys and matching patterns efficiency.

**Comment by sayanarijit** [comment] 2021-05-24 13:32
> I'm curious, what would be difficult to implement here?
> 
> As for performance, have you considered a cache, to search _only once_ the settings for a given mime type, and always use the same on subsequent needs?

Sounds cool. Can please provide a minimal prototype implementation for xplr?

**Comment by bew** [comment] 2021-05-24 16:20
Not anytime soon, I'm a Rust beginner who happen to have a few ideas from times to times, but not enough time to do them ATM. :eyes:

**Comment by sayanarijit** [comment] 2021-05-24 16:25
No issues 👍
And thanks for the suggestion. I'll keep it in mind.

**Comment by sayanarijit** [comment] 2021-05-25 09:24
Going with the no-pattern matching logic.

You can defing mime types like

```lua
xplr.config.node_types.mime_essence = {
  ["video"] = {
    ["*"] = {
      meta = { icon = "📽" },
     },
  }
}
```

**Comment by sayanarijit** [comment] 2021-05-25 17:10
I think the issue is solved. Hence closing this.

**Closed by sayanarijit** 2021-05-25 17:10 UTC
